spring:
  config:
    activate:
      on-profile: development
  messages:
    cache-duration: -1
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-doma2-rest-sample?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: passw0rd
  flyway:
    enable: false
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.bigtreetc.sample: DEBUG

####
# アプリケーションの設定
application:
  security:
    jwt:
      access-token:
        signing-key: ${JWT_ACCESS_TOKEN_SIGNING_KEY:rECsevtFUhG4Up8GU3CVZNs9}
        expired-in: 600000
      refresh-token:
        timeout-hours: 2
  cors:
    allowed-origins: "*"
